# Generated by Django 4.2.4 on 2023-08-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Date_of_arrival',
            new_name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='issued_to',
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_names',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
