# Generated by Django 4.2.4 on 2023-08-08 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spareApp', '0002_rename_date_of_arrival_product_arrival_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='part_name',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='item',
            new_name='part_purchased',
        ),
        migrations.AddField(
            model_name='product',
            name='branch_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='date_of_purchase',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
    ]
