# Generated by Django 4.2.4 on 2023-08-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareApp', '0006_alter_product_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.IntegerField(default=0),
        ),
    ]
