# Generated by Django 4.2.4 on 2023-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareApp', '0009_alter_product_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
